server {
    listen 80;
    listen [::]:80;

    server_name coolhost2.test www.coolhost2.test;
    root /sandbox/sandbox/coolhost/coolhost;
    index index.html index.htm index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log /var/log/nginx/coolhost2.test-access.log;
    error_log /var/log/nginx/coolhost2.test-error.log error;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }
}
