server {
    listen 80;
    listen [::]:80;

    server_name keel-wp.test www.keel-wp.test;
    root /sandbox;
    index index.html index.htm index.php;

    charset utf-8;

    location ~* \.(jpg|jpeg|png|gif|svg|webp|mp4|webm)$ {
        valid_referers none blocked server_names *.keel-wp.test keel-wp.test;
        if ($invalid_referer) {
            return 403;
        }
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log /var/log/nginx/keel-wp.test-access.log;
    error_log /var/log/nginx/keel-wp.test-error.log error;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }
}
